`Grading Formula`

0.3 weekly quizzes   
0.2 SGA1  
0.2 SGA2  
0.3 final project  

**deadlines: Sunday 10:59 AM MSK**

`Webinar Schedule`

- January 13, 12:00 — 13:00, Q&A 1
- January 15, 20:00 — 21:00, Q&A 2
- January 27, 12:00 — 13:00, Q&A 3
- January 29, 20:00 — 21:00, Q&A 4
- February 10, 12:00 — 13:00, Q&A 5
- February 12, 20:00 — 21:00, Q&A 6

# `Week 1 - Matrices`

In [4]:
import numpy as np
from scipy.linalg import lu
import numpy.linalg as la

def row_echelon_form(matrix): 
    matrix = np.array(matrix, dtype=float) 
    lead = 0 
    rowCount = len(matrix) 
    columnCount = len(matrix[0]) 
    for r in range(rowCount): 
        if lead >= columnCount: 
            return matrix 
        i = r 
        while matrix[i][lead] == 0: 
            i += 1 
            if i == rowCount: 
                i = r 
                lead += 1 
                if columnCount == lead: 
                    return matrix 
        matrix[[i, r]] = matrix[[r, i]] 
        if matrix[r][lead] != 0: 
            matrix[r] = matrix[r] / matrix[r][lead] 
        for i in range(rowCount): 
            if i != r: 
                if matrix[i][lead] != 0: 
                    matrix[i] = matrix[i] - matrix[i][lead] * matrix[r] 
        lead += 1 
    return matrix

`Using inverse matrix to solve linear equations`

In [66]:
# setting arrays
a = np.array([[4,2,2], [3,2,1], [-2,-1,-2]])
b = np.array([[5], [7], [-3]])

# finding inverse
inv = np.linalg.inv(a)

# calculating solutions
x = np.dot(inv, b)

print(f"{x}")

[[-2.5]
 [ 7. ]
 [ 0.5]]


`find the row echelon reduced matrix form`

In [85]:
# find the row echelon reduced matrix form

matrix = np.array([[2,1], [2,-1]])

# find the row echelon reduced matrix
for i in range(0, len(matrix)):
    for j in range(i+1, len(matrix)):
        if matrix[i][i] == 0:
            matrix[i], matrix[j] = matrix[j], matrix[i]
        else:
            matrix[j] = matrix[j] - matrix[i] * (matrix[j][i] / matrix[i][i])

for i in range(len(matrix)-1, -1, -1):
    for j in range(i-1, -1, -1):
        matrix[j] = matrix[j] - matrix[i] * (matrix[j][i] / matrix[i][i])
    matrix[i] = matrix[i] / matrix[i][i]

print(matrix)

[[1 0]
 [0 1]]


In [63]:
matrix = np.array([[2,1,1], [3,2,1], [2,1,2]])

# find the matrix inverse
inv = np.linalg.inv(matrix)

print(inv)


[[ 3. -1. -1.]
 [-4.  2.  1.]
 [-1.  0.  1.]]


In [79]:
# Choose an elementary transformation matrix T that transforms matrix A to an upper triangular one, where

a = np.array([ [2,1], [2,-1]])

# find the elementary transformation matrix  that transforms A to an upper triangular matrix
t = np.array([[1,1], [0,1]])

np.dot(a,t)

array([[2, 3],
       [2, 1]])

In [81]:
# LU decomposition

a = np.array([[2,1], [2,-1]])

# find the LU decomposition
l = np.array([[1,0], [1,1]])
u = np.array([[2,1], [0,1]])

np.dot(l,u)


array([[2, 1],
       [2, 2]])

In [84]:
m = np.array([[2,1], [0,-2]])
t = np.array([[1,1], [0,1]])

np.dot(m,t)

array([[ 2,  3],
       [ 0, -2]])

In [91]:
m = np.array([[1,2], [3,4]])

np.linalg.inv(m) * -2

# get upper triangular matrix
np.triu(m)

# get lower triangular matrix
np.tril(m)

# apply LU decomposition
np.dot(np.tril(m), np.triu(m))

array([[ 1,  2],
       [ 3, 22]])

`lower and upper matrices`

In [110]:
m = np.array([[2,1], [2,-1]])

low = np.tril(m)

up = np.triu(m)

print(low, up, sep='\n\n')


[[ 2  0]
 [ 2 -1]]

[[ 2  1]
 [ 0 -1]]


`plu decomp using scipy`


In [104]:
# plu decomp using scipy

B = np.array([[0,0,1], [0,2,2], [3,0,4]])

P, L, U = lu(B)

# use allclose
np.allclose(np.dot(np.dot (P, L), U), B)

True

In [119]:
# practice quizz 1

# 1
m1 = np.array([[1,1,0], [0,1,0], [0,0,-1]])
m2 = np.array([[1,2,3], [0,1,0], [-1,-2,-3]])
m3 = np.array([[1,1,1], [1,1,1], [-1,-1,-1]])
m4 = np.array([[1,-1], [0,1], [-1,0]])

sum(m1 @ (m2-m3) @ m4)

array([[-2,  2],
       [ 0,  1],
       [-2,  1]])

In [120]:
# 2
a = np.array([[1,0,2], [2,-1,0], [0,1,0]])
b = np.array([[0,2], [1,3], [1,0]])
c = np.array([[0,-2,2], [1,0,0]])

(c @ np.transpose(a) @ b) - (np.transpose(b) @ a @ np.transpose(c))

array([[  0,  12],
       [-12,   0]])

In [122]:
# 3
c = np.array([[1,2,1,2]])
b = np.array([[0,2,1,3], [-1,0,6,4], [1,0,1,-7], [0,7,0,1]])

np.transpose(c) @ c @ b 

array([[-1, 16, 14,  6],
       [-2, 32, 28, 12],
       [-1, 16, 14,  6],
       [-2, 32, 28, 12]])

In [124]:
# 4
m = np.array([[0,1,0,1], [1,1,1,1], [2,3,4,5], [5,7,9,11]])

print(row_echelon_form(m))

[[ 1.  0.  0. -1.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


In [125]:
# 5
m = np.array([[1,1,1,1], [2,2,2,2], [-1,-1,1,1], [3,5,-1,-3]])

print(row_echelon_form(m))

[[ 1.  0.  0.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


In [217]:
# 6
a = np.array([[2,1], [3,2]])
b = np.array([[-1,-3],[1,4]])
c = np.array([[2,-4], [-1,1]])

# Solve the matrix equation 𝐴𝑋𝐵^T=𝐶 using LU
a_inv = np.linalg.inv(a)
b_inv = np.linalg.inv(b)

np.dot(a_inv, np.dot(c, np.transpose(b_inv))).sum()



-1.0000000000000009

In [136]:
# 9

a = np.array([[3,5,-1], [-4,1,2], [0,1,0]])

np.linalg.inv(a)


array([[  1. ,   0.5,  -5.5],
       [  0. ,   0. ,   1. ],
       [  2. ,   1.5, -11.5]])

In [143]:
# 10
matrix = np.array([[2,-3,1], [4,2,-5], [-2,2,1]])
b = np.array([[2], [-1], [-5]])

inv = np.linalg.inv(matrix)

sol = np.dot(inv, b)

# solution in a fraction view
sol

array([[-2.55555556],
       [-3.44444444],
       [-3.22222222]])

In [279]:
# Week 1 quizz

# 6
a = np.array([-1, 5, 1, 4, 6])
b = np.array([0, 8, -3, 4, -1])

print(f"6: {a@b}")

# 7
a = np.array([[3,1,-2], [1,1,4]])
b = np.array([[2,-1], [0,-5], [-1,0]])
c = np.array([[4,3,-5], [4,1,0], [-3,1,0]])

print(f"7: {(a@c@b).sum()}")

# 8
A = np.array([[1,5,-2,1], [3,16,-3,11], [0,0,6,10], [-5,-25,10,-1]])
b = np.array([[4], [19], [2], [-12]])

print(f"8:{np.linalg.solve(A, b).round()}")

# 9
matrix = np.array([[1,-2,3], [-3,0,2], [1,-1,4]])
b = np.array([[5], [2], [6]])

inv = np.linalg.inv(matrix)

sol = np.dot(inv, b)

print(f"9: {sol}")

# 11
matrix = np.array([[3,5,-1], [-4,1,2], [0,1,0]])
print(f"11:\n {np.linalg.inv(matrix)}")

# 12. Using Gaussian elimination, find the inverse of M and write down the largest element of the inverse matrix
M = np.array([[1,1,1,1], [-2,3,2,1], [0,1,1,1], [1,3,1,-2]])

print(f"12: {round(np.linalg.inv(M).max())}")

#17
c = np.array([[1,2,3,-1]])
b = np.array([[1,3,1,0], [1,0,-1,2], [0,0,1,2], [-1,1,0,1]])

print(f"17:\n {np.transpose(c) @ c @ np.transpose(b) @ b}")

#18
m = np.array([[1,1,2,-1], [-1,0,3,2], [2,-1,1,0], [0,1,5,1]])
print(f"18:\n {row_echelon_form(m)}")

# Find LU decomposition of the matrix A; such that the matrix 𝐿 has unit diagonal elements. Fill the gaps in the matrix 𝐿 and list the numeric value 𝑦
A = np.array([[-3,4,0], [1,-3,2], [6,7,1]])

6: 47
7: -42
8:[[-4.]
 [ 0.]
 [-3.]
 [ 2.]]
9: [[ 0.23529412]
 [-0.35294118]
 [ 1.35294118]]
11:
 [[  1.    0.5  -5.5]
 [  0.    0.    1. ]
 [  2.    1.5 -11.5]]
12: 21
17:
 [[  6  30  15  -6]
 [ 12  60  30 -12]
 [ 18  90  45 -18]
 [ -6 -30 -15   6]]
18:
 [[ 1.          0.          0.         -0.75      ]
 [ 0.          1.          0.         -1.08333333]
 [ 0.          0.          1.          0.41666667]
 [ 0.          0.          0.          0.        ]]
18:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [272]:
## Task 3
# Find the sum of all matrix elements whose absolute value is greater than 5 using np.where
b = np.array([[ -6,  -7,  -5,   0],
       [-15,   2, -13,  -5],
       [  8,   4,  10,   8],
       [ -1,  -9,   7,  -4]])

np.where(abs(b) > 5, b, 0).sum()


# Create an identity matrix of the necessary size and subtract it from A.  Save the result to a variable **ans5**

A = np.array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])

ans5 = A - np.eye(6)

In [275]:
# Find the PLU decomposition and assert that by multiplying the matrices in the decomposition you get the original matrix back. Submit the matrix U as the answer.

m = np.array([[ 12, -13,   2,   2, -11],
       [  1,   4,  11,  11,  -5],
       [ 13,  -5,   9,  12,  -2],
       [  5, -13,  12,   3,   5],
       [ -9,  11,  -1,  -6,  -5]])


p, l, u = scipy.linalg.lu(m)

np.allclose(m, p @ l @ u)

True

# `Week 2 - Full rank decomposition and systems of linear equations`

`Vector spaces`  
Consider some set V of elements x, y, z, ... It is called a vector space (or a linear space), if
- for any two elements $x, y \in$ V there exists their sum $z = x + y \in V$;
- for each $x \in V$ and each real number $a$, there exists their product $\lambda x \in V$.

In [4]:
m = np.array([[1,2,3], [5,6,7], [4,8,9]])

la.matrix_rank(m)

3

In [6]:
m = np.array([[4,4,8], [5,10,20]])

row_echelon_form(m)

array([[1., 0., 0.],
       [0., 1., 2.]])

In [50]:
m = np.array([[1,1,-1,2,1], [1,0,1,-1,2], [3,1,1,0,5]])

row_echelon_form(m)

array([[ 1.,  0.,  1., -1.,  2.],
       [-0.,  1., -2.,  3., -1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [67]:
m = np.array([[5,-1,-1,3,1], [5,-1,5,3,3], [5,-1,-7,-9,-1]])

# row_echelon_form(m)

la.matrix_rank(m)

3

In [70]:
# check linear dependence
m = np.array([[1,3,7], [0,0,-2], [0,6,19]])

row_echelon_form(m)



array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

In [73]:
la.matrix_rank(np.array([[12,14], [18,21]]))

1

In [75]:
la.matrix_rank(np.array([[3,-1,1,9], [-3,4,1,1], [6,5,2,8], [1,1,1,1]]))

4

In [76]:
row_echelon_form(np.array([[1,3,2], [2,-1,3], [3,-5,4], [1,17,4]]))

array([[ 1.        ,  0.        ,  1.57142857],
       [-0.        ,  1.        ,  0.14285714],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [77]:
row_echelon_form(np.array([[1,2,3,4], [2,3,4,1], [3,4,1,2], [4,1,2,3]]))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
m = np.array([[4,1,-8,5,2], [-3,1,4,7,1], [1,2,-4,12,1], [1,1,1,1,1]])
m_p = np.array([[4,1,-8,5], [-3,1,4,7], [1,2,-4,12], [1,1,1,1]])
# comparing ranks
la.matrix_rank(m) == la.matrix_rank(m_p)


False

In [85]:
m = np.array([[1,0,3,1], [5,-1,1,0], [3,7,-1,8], [-3,-2,1,-3]])
b = np.array([[1], [1], [1], [-1]])

inv = la.inv(m)

(inv @ b).sum()

0.0

In [94]:
# How many vectors are there in the basis of solution set for Ax=0?
matrix = np.array([[4,5,7,-3,1], [11,8,-4,2,0]])

5 - la.matrix_rank(matrix)




3

In [99]:
m = np.array([[5,2,1,-4], [0,3,4,-2], [1,3,4,-2], [-1,1,0,0]])
b = np.array([[1], [-2], [3], [0]])

inv = la.inv(m)

(inv @ b).round(2)

array([[ 5. ],
       [ 5. ],
       [-0. ],
       [ 8.5]])

In [100]:
m = np.array([[1,-1,3,1], [3,-2,2,-1], [2,1,1,-3], [1,-3,2,1]])
b = np.array([[4], [-1], [1], [0]])

inv = la.inv(m)

(inv @ b).sum()

2.0000000000000004

In [101]:
m = np.array([[3,-2,-2,-2], [6,3,-1,1], [3,-1,-1,2]])

row_echelon_form(m)

array([[ 1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , -1.75],
       [ 0.  ,  0.  ,  1.  ,  5.75]])

In [51]:
# W2Q2
la.matrix_rank(np.array([[1,4,5], [-5,8,9], [-12,8,8]]))

2

In [54]:
# W2Q3
la.matrix_rank(np.array([[4,8,1,-9], [0,5,1,3], [2,9,1,4], [1,7,1,3.5]]))

3

In [55]:
#W2Q4
# find number of free variables of the matrix
m = np.array([[0,2,7,-1], [-1,2,5,5], [-4,13,0,6]])
row_echelon_form(m)

array([[ 1.        ,  0.        ,  0.        , -6.61333333],
       [ 0.        ,  1.        ,  0.        , -1.57333333],
       [-0.        , -0.        ,  1.        ,  0.30666667]])

In [60]:
# W2Q5
# Does the SLAE have solutions? Use Rouche-Capelli Theorem

m = np.array([[-8,-1,5], [-5,2,7], [0,3,8]])
m_p = np.array([[-8,-1,5, 1], [-5,2,7,0], [0,3,8,2]])

# comparing ranks
la.matrix_rank(m) == la.matrix_rank(m_p)


True

Week 3

In [2]:
m = np.array([[1,0,3], [1,4,3], [2,6,7]])

# find if all vectors from m are linearly independent
la.matrix_rank(m) == m.shape[0]

True

In [4]:
m = np.array([[1,0,2,0], [1,2,1,3], [0,1,3,0], [0,1,5,6], [4,1,3,0]])

# find if all vectors from m are linearly independent
la.matrix_rank(m)


4

In [3]:
# Find the scalar product ⟨x,y⟩ of vectors x and y in R^3

x = np.array([2,-2, 1])
y = np.array([-4,3,0])

(x @ y).sum()

# find the vector length of x 

np.linalg.norm(y)

# Find the cosine of the angle between vectors x and y from the previous tasks. Round your answer to hundredths if needed.

(x @ y).sum() / (np.linalg.norm(x) * np.linalg.norm(y))

# Are vectors x and y from the previous tasks orthogonal?

# np.isclose((x @ y).sum(), 0)

-0.9333333333333333

In [27]:
# Find the cosine of the angle between vectors x and y from the previous tasks. Round your answer to hundredths if needed.

np.cos((x @ y).sum() / (np.linalg.norm(x) * np.linalg.norm(y)))


0.5951585994691279

In [36]:
# A company’s shares cost $100 on the first day, $200 on the second one and $150 on the third one. Using linear regression, try to predict the cost of the shares on the fourth day. Find coefficients k and b for a line y = kx + b that corresponds to the shares’ costs. Enter coefficients in the given order separated by space. For example, if k=1 and b=2, he answer should be “1 2”. If there are no coefficients, enter “None”. Round them to hundredths if needed.

x = np.array([1,2,3])
y = np.array([100,200,150])

k, b = np.polyfit(x, y, 1)

print(round(k), round(b))

25 100


Week 3 final quiz

In [37]:
# Find the length of the vector x in the 5-dimensional space. Please enter a numeric value

x = np.array([8,6,4,2,1])

np.linalg.norm(x)

11.0

In [40]:
# Find the length of x=(1,−7,3) is a vector in Euclidean space, the coordinates are given with respect to some orthogonal basis.

x = np.array([1,-7,3])

np.linalg.norm(x) == np.sqrt(59)

True

In [77]:
# Find the angle between x and y, if x = (1,-3,0)^T, y = (0,1,-7)^T, where x, y are vectors in R^3

x = np.array([1,-3,0])
y = np.array([0,1,-7])

# find the angle
np.arccos((x.T @ y.T).sum() / (np.linalg.norm(x) * np.linalg.norm(y))) == np.arccos(-3/(10*np.sqrt(5)))

True

In [4]:
# Write down the cos of the angle between x and y, if x = (3,1,2,5)^T, y = (-1,4,-3,0), x, y are vectors in Euclidean space. Please enter a numeric value rounded to the nearest hundredth.

x = np.array([3,1,2,5])
y = np.array([-1,4,-3,0])

(x.T @ y.T).sum() / (np.linalg.norm(x) * np.linalg.norm(y))

-0.15701857325533194

In [97]:
# Does the following set of vectors form a basis in Rn?

x1 = np.array([1,1,1,1])
x2 = np.array([2,3,0,-1])
x3 = np.array([1,2,1,3])
x4 = np.array([1,3,-1,0])

# Does the following set of vectors x1,x2,x3,x4 form a basis in Rn?

# find the rank of the matrix
la.matrix_rank(np.array([x1,x2,x3,x4])) == 4


False

In [98]:
x, y = np.array([9,-2,4]), np.array([2,-5,2])

# find the dot product
(x @ y).sum()

36

In [120]:
# Find the approximation to the solution of Ax=b. Use least squares method.

a = np.array([[3,-5], [1,-7], [0,1]])
b = np.array([0,2,5])

# find the solution
print(round(la.lstsq(a, b, rcond=None)[0][0],5)  == round(-24/133,5), round(la.lstsq(a, b, rcond=None)[0][1],5)  == round(-23/133,5))

True True


In [18]:
# Find eigenvalue (or eigenvalues) of matrix A 

A = np.array([[2,2], [2,-1]])

# find eigenvalues
eigenval = la.eigvals(A)

# Using matrix and its eigenvalues from the previous task, choose all eigenvectors of A
eigenvec = la.eig(A)[1]

# Using matrix, eigenvalues, and eigenvectors from the previous tasks, find matrix L from spectral decomposition of matrix A.

# find the diagonal matrix
np.diag(eigenval)

# Using matrices, eigenvalues, and eigenvectors from the previous tasks, find matrix U from spectral decomposition of matrix A

# find the matrix U
eigenvec


array([[ 0.89442719, -0.4472136 ],
       [ 0.4472136 ,  0.89442719]])

In [26]:
# Let's consider a linear manifold P=x0+L Given that the orthogonal component of the vector x-x0 is (9 −12 0)^T, what is the distance 𝜌(x,P)? Please enter a numeric value.

x0 = np.array([1,1,1])
x = np.array([10, -11, 1])
L = np.array([1,1,1])

# find the distance
np.linalg.norm(x - x0 - (x - x0) @ L * L)

15.297058540778355

In [27]:
# Find the QR decomposition of matrix A where diagonal elements in R are negative. Write down the sum of elements in matrix R as the answer to this question

A = np.array([[3,1,-2], [1,1,1], [-1,2,4]])
q, r = la.qr(A)
r.sum()

-7.852886724691755

In [15]:
# Find SVD for A

A = np.array([[2,4], [1,2], [0,0]])

# find SVD
u, s, vh = la.svd(A)

print(f"{u}\n\n{s}\n\n{vh}")

[[-0.89442719 -0.4472136   0.        ]
 [-0.4472136   0.89442719  0.        ]
 [ 0.          0.          1.        ]]

[5. 0.]

[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


In [16]:
# Find SVD for A

A = np.array([[0,0], [3,4], [0,0]])

# find SVD
u, s, vh = la.svd(A)

print(f"{u}\n\n{s}\n\n{vh}")

[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

[5. 0.]

[[-0.6 -0.8]
 [-0.8  0.6]]


In [18]:
# Find singular values for A and enter their sum. Please enter a numeric value rounding your answer to the nearest hundredth, if necessary

A = np.array([[4,-1], [-1,4]])

# find singular values
la.svd(A)[1].sum()


8.0

In [25]:
# Find singular values for A and enter their sum. Please enter a numeric value rounding your answer to the nearest hundredth, if necessary

np.sum(la.svd(np.array([[-2, 0, 1], [0,-2,1], [1,1,-1]]))[1])


5.0